# Generated by Django 5.0.7 on 2024-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=200)),
                ('question2', models.CharField(max_length=200)),
                ('question3', models.CharField(max_length=200)),
                ('question4', models.CharField(max_length=200)),
                ('question5', models.CharField(max_length=200)),
                ('question6', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
