# Generated by Django 5.0.7 on 2024-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='phone',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question5',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question6',
            field=models.CharField(max_length=10),
        ),
    ]
